apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-distancia-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao-distancia
  template:
    metadata:
      labels:
        app: conversao-distancia
    spec:
      containers:
      - name: conversao-distancia
        image: tscampos/conversao-distancia:v1
        resources: {}
        ports:
        - containerPort: 5000
