apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: conversao-distancia
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 5000
 
