apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-peso-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao-peso
  template:
    metadata:
      labels:
        app: conversao-peso
    spec:
      containers:
      - name: conversao-peso
        image: tscampos/conversao-peso:v1
        resources: {}
        ports:
        - containerPort: 80
