apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: tscampos/rotten-potatoes:v1
        ports:
        - containerPort: 5000
        resources: {}
        env:
          - name: MONGODB_HOST
            value: mongo-service
          - name: MONGODB_USERNAME
            value: mongodbuser
          - name: MONGODB_PASSWORD
            value: mongodbpwd
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_DB
            value: "admin"