apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer #ClusterIP ou NodePort
  selector:
    app: api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
 
